name: Render and deploy Quarto files
on:
  push:
  pull_request:    
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
