name: Render and Publish Quarto
on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Render GitHub
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
