name: Render and deploy Quarto files
on:
  push:
  pull_request:    
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: results/blog
          target: docs
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
